"""empty message

Revision ID: 161f26b6e775
Revises: 76a7c4e2ccad
Create Date: 2021-01-12 09:48:35.595172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161f26b6e775'
down_revision = '76a7c4e2ccad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
